### ISSUE TITLE
Assertion failed: !intv.is_bottom(), file E:\ebpf-verifier\src\crab\split_dbm.cpp, line 953

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#736]
Test case:

```yaml
test-case: repro

pre: [r0.type=number]

code:
  <start>: |
    if r0 s< 0x8000 goto <exit>
    r0 %= 0x808
  <exit>: |
    exit

post:
  - r0.type=number
```

This was found while fuzzing using uBPF libfuzzer. Issue appears to be in the mod operation.
