### ISSUE TITLE
Signed comparisons of pointers against 0 should only be permitted for == or !=, not >, >=, <, or <=

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#757]
Sample test case that should fail, but doesn't.

```yaml
---
test-case: comparison against context ptr as 32bit signed

pre:
  - "r1.type=ctx"
  - "r1.svalue=[1, 2147418112]"
  - "r1.ctx_offset=0"

code:
  <start>: |
    if r1 s< 1 goto <exit>
    r0 = 1
  <exit>: |
    exit

post:
  - r0.svalue=1
  - r0.type=number
  - r0.uvalue=1
  - r1.ctx_offset=0
  - r1.svalue=[1, 2147418112]
  - r1.type=ctx

messages:
  - "0: Invalid type (r1.type == number)"

```
