### ISSUE TITLE
assert(!intv.is_bottom()) in void SplitDBM::set(const variable_t x, const interval_t& intv)

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#760]
Test case that triggers it
```yaml
test-case: 32bit multiplication - uninitialized register

pre: []

code:
  <start>: |
    w0 *= 1207967752
    w0 *= r0

post: []

message: []
```
