### ISSUE TITLE
check that unsigned right shift by 0 is idempotent fails

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#766]
```yaml
test-case: check that unsigned right shift by 0 is idempotent

pre:
  - r0.type=number
  - r0.svalue=-8863041185711652825
  - r0.uvalue=9583702887997898791
  - r1.type=number
  - r1.svalue=-8863041185711652825
  - r1.uvalue=9583702887997898791

code:
  <start>: |
    r0 >>= 0
    if r1 == r0 goto <one>
    r2 = 0
    exit
  <one>: |
    r2 = 1
    exit

post:
  - r0.type=number
  - r0.svalue=-8863041185711652825
  - r0.uvalue=9583702887997898791
  - r1.type=number
  - r1.svalue=-8863041185711652825
  - r1.uvalue=9583702887997898791
  - r0.uvalue=r1.uvalue
  - r0.svalue=r1.svalue
  - r2.type=number
  - r2.svalue=1
  - r2.uvalue=1

messages:
  - "1:2: Code is unreachable after 1:2"
```

Fails with:
```
test case: check that unsigned right shift by 0 is idempotent
Unexpected properties: None
Unseen properties:
  [
    r0.svalue=-8863041185711652825, r0.svalue=r1.svalue, r0.type=number, r0.uvalue=9583702887997898791, r0.uvalue=r1.uvalue,
    r1.svalue=-8863041185711652825, r1.type=number, r1.uvalue=9583702887997898791,
    r2.svalue=1, r2.type=number, r2.uvalue=1]
Unexpected messages:
  CRAB ERROR: number_t 9583702887997898791 does not fit into __int64
Unseen messages:
  1:2: Code is unreachable after 1:2
```
