### ISSUE TITLE
Should not permit returning lower 32bits of pointer as r0

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#771]
Two test cases, one with 64bit that passes and one with 32bit that fails:
```yaml
---
test-case: 64-bit return context pointer

pre:
  - r0.uvalue=[0, 4294967295]
  - r0.svalue=r0.uvalue
  - r0.type=number
  - "r1.ctx_offset=0"
  - "r1.svalue=[0, 4294967295]"
  - "r1.svalue=r1.uvalue"
  - "r1.type=ctx"
  - "r1.uvalue=[0, 4294967295]"

code:
  <start>: |
    r0 = r1
    exit

post:
  - r0.ctx_offset=0
  - r0.svalue=[0, 4294967295]
  - r0.svalue=r0.uvalue
  - r0.svalue=r1.svalue
  - r0.svalue=r1.uvalue
  - r0.type=ctx
  - r0.uvalue=[0, 4294967295]
  - r0.uvalue=r1.svalue
  - r0.uvalue=r1.uvalue
  - r1.ctx_offset=0
  - r1.svalue=[0, 4294967295]
  - r1.svalue=r1.uvalue
  - r1.type=ctx
  - r1.uvalue=[0, 4294967295]

messages:
  - "1: Invalid type (r0.type == number)"

---
test-case: 32-bit return context pointer

pre:
  - r0.uvalue=[0, 4294967295]
  - r0.svalue=r0.uvalue
  - r0.type=number
  - "r1.ctx_offset=0"
  - "r1.svalue=[0, 4294967295]"
  - "r1.svalue=r1.uvalue"
  - "r1.type=ctx"
  - "r1.uvalue=[0, 4294967295]"

code:
  <start>: |
    w0 = w1
    exit

post:
  - r1.ctx_offset=0
  - r1.svalue=[0, 4294967295]
  - r1.svalue=r1.uvalue
  - r1.type=ctx
  - r1.uvalue=[0, 4294967295]

messages:
  - "1: Invalid type (r0.type == number)"
```
