### ISSUE TITLE
Count down loop termination check is wrong

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#785]
```yaml
test-case: Count down loop - incorrectly passes
options: ["termination"]

pre: []

code:
  <start>: |
    r0 = 0
    r1 = 10
  <loop>: |
    r1 -= 1
    if r1 > 1 goto <loop>
    exit

post:
  - pc[2]=[1, +oo]
  - r0.svalue=0
  - r0.type=number
  - r0.uvalue=0
  - r1.svalue=[0, 1]
  - r1.type=number
  - r1.uvalue=[0, 1]

messages:
  - "2: Loop counter is too large (pc[2] < 100000)"
```

Test case should fail, but passes. It clearly terminates within 10 iterations, but termination check things it's unbounded.
