### ISSUE TITLE
When storing to the stack verifier fails to truncate values

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#841]
```yaml
test-case: Round trip min int on stack

pre: ["r10.type=stack", "r10.stack_offset=512"]

code:
  <start>: |
    r0 = -2147483648
    *(u32 *)(r10 - 4) = r0
    r0 = *(u32 *)(r10 - 4)

post:
  - r10.stack_offset=512
  - r10.type=stack
  - r0.type=number
  - r0.svalue=2147483648
  - r0.uvalue=2147483648
  - s[508...511].type=number
  - s[508...511].svalue=-2147483648
  - s[508...511].uvalue=2147483648
```

```
test case: Round trip min int on stack
Unexpected properties:
  [
    r0.svalue=-2147483648, r0.uvalue=18446744071562067968,
    s[508...511].uvalue=18446744071562067968]
Unseen properties:
  [
    r0.svalue=2147483648, r0.uvalue=2147483648,
    s[508...511].uvalue=2147483648]
Unexpected messages: None
Unseen messages: None
```

Note the following is impossible:
    s[508...511].uvalue=18446744071562067968]

Reading 4 bytes from stack can not result in a 8 byte value.

**Comment by Alan-Jowett** [comment]
Clearer example:
```yaml
test-case: Round trip min int on stack with truncation to 8 bits

pre: ["r10.type=stack", "r10.stack_offset=512"]

code:
  <start>: |
    r0 = -1
    *(u8 *)(r10 - 1) = r0
    r0 = *(u8 *)(r10 - 1)

post:
  - r10.stack_offset=512
  - r10.type=stack
  - r0.svalue=255
  - r0.uvalue=255
  - s[511].svalue=-1
  - s[511].uvalue=255
```
```
Unexpected properties:
  [
    r0.svalue=-1, r0.type=number, r0.uvalue=18446744073709551615,
    s[511].type=number, s[511].uvalue=18446744073709551615]
Unseen properties:
  [
    r0.svalue=255, r0.uvalue=255,
    s[511].uvalue=255]
```
